# Generated by Django 5.2.4 on 2025-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(max_length=100)),
                ('profissional', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=15)),
            ],
        ),
    ]
